#!/bin/bash
#Authors Amanda Nygårds and Fabian Otterskog

#GLOBAL VARIABLES
# The home directory of System Manager.
SMHOME=pwd

#Create menu
printMenu() {
echo '*********************************************'
echo $'\t' "SYSTEM MANAGER (BETA)"
echo '*********************************************'
echo ua - User Add$'\t'$'\t'"(Create an new user)"
echo ul - User List$'\t'$'\t'"(List all login users)"
echo uv - User View$'\t'$'\t'"(View user properties)"
echo um - User Modify$'\t'"(Modify user properties)"
echo ud - User Delete$'\t'"(Delete a login user)"
echo ga - Group Add$'\t'$'\t'"(Create a new group)"
echo gl - Group List$'\t'$'\t'"(List all groups, not system groups)"
echo gv - Group View$'\t'$'\t'"(List all users in a group)"
echo gm - Group Modify$'\t'"(Add/remove user to/from a group)"
echo gd - Group Delete$'\t'"(Delete a group, not system groups)"
echo fa - Folder Add$'\t'$'\t'"(Create a new folder)"
echo fl - Folder List$'\t'$"(View content in a folder)"
echo fm - Folder Modify$'\t'"(Modify folder properties)"
echo fd - Folder Delete$'\t'"(Delete a folder)"
echo ss - SSH Server$'\t'$'\t'"(Manage SSH Server)"
}

#Adds a user with useradd shell prompt
userAdd() {
read -p 'Username:' usrname
sudo adduser $usrname
}

#Lists all users
userlist() {
echo '*********************************************'
echo 'Current login users on the system:'
echo '*********************************************'
awk -F: '$3 >= 1000 && $4 <= 60000 && $1 != "nobody" {print $1}' /etc/passwd
echo '*********************************************'
}

userView() {
# Read all user IDs.
# -F sepstring.
echo ----------------------------------------
echo Current login users on the system:
awk -F: '$3 >= 1000 && $4 <= 60000 && $1 != "nobody" {print $1}' /etc/passwd
}

#modify a user
usermod() {
echo '*********************************************'
echo $'\t' "Modify User"
echo '*********************************************'
echo "Which user to modify?"
read -p 'User to modify:' usrname
echo "what do you want to modify? Your oprions are:"
echo "Nm (Name)"
echo "Pw (Password)"
echo "Ud (User ID)"
echo "Gd (Group ID)"
echo "Cm (Comment)"
echo "Hd (Home ditectory)"
echo "Sh (Shell)"
read -p 'Option to modify: ' modoption
read -p 'New value: ' newmod
if [ $modoption = "Pw" ]
then
        usermod -p $newmod $usrname
elif [ $modoption = "Ud" ]
then
        usermod -u $newmod $usrname
elif [ $modoption = "Gd" ]
then
        usermod -g $newmod $usrname
elif [ $modoption = "Cm" ]
then
        usermod -c $newmod $usrname
elif [ $modoption = "Hd" ]
then
        usermod -d $newmod $usrname
elif [ $modoption = "Sh" ]
then
        usermod -s $newmod $usrname
elif [ $modoption = "Nm" ]
then
        usermod -l $newmod $usrname
fi
echo "Done"
}

#Delete user including home directory
userDel() {
echo "WARNING: You are about to delete a user."
read -p 'User to remove:' usrname
sudo userdel -r $usrname
}

#add a group
groupAdd() {
read -p 'Name of new group: ' gName
groupadd $gName
}

GroupView(){
echo "whitch group do you want to view?"
read -p 'groupname: ' gName
echo "the members of $gName are: "
cat /etc/group | egrep $gName | awk -F: '{print $4}' | sed y/,/'\n'/
}

groupMod() {
echo '*********************************************'
echo $'\t' "Modify Group"
echo '*********************************************'
echo "Do you want to add to a group or remove from a group?"
read -p '(add/remove):' input
if ($input != "add" || $input != "remove"); 
    echo "Error: No valid input for (add/remove)"
    fi
echo "Which user to modify?:"
read -p 'Username' usrname
echo "Which group to add/remove from?:"
read -p 'Group name:' grpname
if ($input == "remove");
    echo "Removing '$usrname' from group '$grpname'."
    sudo deluser $usrname $grpname

else
    echo "Adding '$username' to group '$grpname'."
    sudo usermod -a -G $grpname $usrname
fi
}

folderAdd () {
read -p 'Path:' move
read -p 'Name of folder:' fname
mv $move
mkdir $fname
mv $SMHOME
}

folderMod() {
read -p 'Path:' move
read -p 'Name of folder' fname
echo "--Options--"
echo rename $'\t'$'\t' - Rename selected folder.
echo privilegies $'\t' - Change privilegies for folder. 
echo stricky bit $'\t' - Change sticky bit.
echo setgid $'\t'$'\t' - Modify setgid.
echo lastmod $'\t' - Check and change last modified attribute.
read -p 'Option:' option
if $option=="rename";
    read -p 'New name:' nfname
    mv $move
    mv $fname $nfname
elif $option=="privilegies";
    read -p 'Set privilegies:' priv
    
}


printMenu
